### ISSUE TITLE
Errors when running dca 

### ISSUE THREAD

**Issue by Nayrouz109** [Sun-lab/ideas_pipeline#1]
Hello team, 

Thank you so much for the amazing IDEAS manuscript. I want to use IDEAS on my dataset and tried to denoise it first with DCA, but I kept getting the below error when running `dca`. I thought I could reach out and ask whether you've encountered a similar error. 

```
`2022-08-23 11:24:08.619181: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory

2022-08-23 11:24:08.619240: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Traceback (most recent call last):
File "/home/nelazzabi/anaconda3/bin/dca", line 8, in <module>
     sys.exit(main())
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/dca/__main__.py", line 152, in main
    from . import train
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/dca/train.py", line 24, in <module>
    from .network import AE_types
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/dca/network.py", line 23, in <module>
    import keras
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/home/nelazzabi/anaconda3/lib/python3.9/site-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`
```

**Comment by liusi2019** [comment]
Dear Nayrouz, 

Thanks a lot for your interest! I didn't get the same issue when using DCA but I did run into some other issues. One thing that might be relevant is the specific versions required by DCA for the packages as specified in
https://github.com/theislab/dca/blob/6abd12469734d743e8c24e0d37cbb006ae1a0f54/setup.py#L10-L19
on DCA GitHub. But I'm not 100% sure that this will be the cause. Feel free to let us know if the issue persists.
